Use setup-ocaml GitHub Action and fix Windows build
mirage/mirage-tcpip pull request #469
Opened 2022-01-03 17:38 UTC by MisterDA

mirage-tcpip requires the same fix than checkseum.
See the result of the CI [here](https://github.com/MisterDA/mirage-tcpip/runs/46937406520).

2022-01-04 09:58 UTC, TheLortex requested changes
Adding Windows and MacOS checks is very useful, thanks. The only requested changed is to remove `ubuntu-latest` as it's redondant with ocaml-ci.

The second commit can probably be dropped as we are removing the freestanding build very soon. 

Even with the second commit, the Windows CI is still failing though, something related to file descriptors. Do you know how hard is it to fix ?

2022-01-04 09:58 UTC, TheLortex commented on .github/workflows/main.yml
> +          - ubuntu-latest
The `ubuntu-latest` platform can be removed as it's already tested by ocaml-ci.

2022-01-04 09:58 UTC, TheLortex commented on freestanding/Makefile
> +ifneq (, $(shell command -v opam || which opam))
Thank you for the fix, but note that the freestanding compilation path will be dropped very soon as it's specific for MirageOS 3.

2022-01-04 10:41 UTC, MisterDA commented
> Adding Windows and MacOS checks is very useful, thanks. The only requested changed is to remove `ubuntu-latest` as it's redondant with ocaml-ci.

Done.

> The second commit can probably be dropped as we are removing the freestanding build very soon.

It's the one I'm interested in! Without it, the opam package cannot be installed on Windows. I'd suggest you use it in the meantime.

> Even with the second commit, the Windows CI is still failing though, something related to file descriptors. Do you know how hard is it to fix ?

I looked into it, it seems that the test is stuck in an infinite loop of

> test.exe: [WARNING] exception Lwt_sys.Not_available("unix_bytes_recvfrom") in recvfrom

`unix_bytes_recvfrom` isn't available in Lwt on Windows: https://github.com/ocsigen/lwt/blob/0fd786536474332dc08b23362261624080c14c44/src/unix/windows_c/windows_not_available.c#L26.
I haven't identified the call site, though.

2022-01-04 11:00 UTC, TheLortex commented
> It's the one I'm interested in! Without it, the opam package cannot be installed on Windows. I'd suggest you use it in the meantime.

ok

> unix_bytes_recvfrom isn't available in Lwt on Windows: https://github.com/ocsigen/lwt/blob/0fd786536474332dc08b23362261624080c14c44/src/unix/windows_c/windows_not_available.c#L26.
I haven't identified the call site, though.

Some investigations thanks to https://sherlocode.com:
- `lwt_unix_bytes_recvfrom` not available
- used in `stub_recvfrom` in `lwt/src/unix/lwt_bytes.ml`
- used in `recvfrom` in `lwt/src/unix/lwt_bytes.ml`
- used in `recvfrom` in `cstruct/lwt/lwt_cstruct.ml`
- used in `listen` in `mirage-tcpip/src/stack-unix/udp{v4,v6,v4v6}_socket.ml`

2022-01-04 12:22 UTC, MisterDA commented
Well, it's documented that `Lwt_bytes` functions related to udp are not implemented on Windows.
https://ocsigen.org/lwt/5.5.0/api/Lwt_bytes#2_IOs

2022-01-04 12:54 UTC, hannesm commented
> Well, it's documented that `Lwt_bytes` functions related to udp are not implemented on Windows.

I understand, but what is the path forward? (a) fine for now, anyone using this stack on Windows will figure it out anyways [i.e. tests are failing] (b) figure out in Lwt (and OCaml) how to support UDP (c) add code here to send and receive UDP datagrams on windows.

I've no clue what is needed for (b) and (c), and would be fine with (a) - maybe worth to disable the tests (with a guard `if not Sys.win32 then`) so that CI will succeed.

2022-01-04 13:07 UTC, MisterDA commented
I think the most useful item would be to add support for UDP in `Lwt_bytes` on Windows. I'm not sure why it wasn't there in the first place. If no one beats me to it I'll probably get my hands dirty and do it, but I can't give an ETA.
In the meantime the best way forward would probably be to disable the test, or test if the function is supported on Windows and disable the test if it is not.

2022-01-04 15:18 UTC, hannesm commented
> In the meantime the best way forward would probably be to disable the test, or test if the function is supported on Windows and disable the test if it is not.

As mentioned, I'm fine with guarding the test(s) with `if not Sys.win32`.

2022-01-05 11:13 UTC, MisterDA commented
I've disabled the failing tests using Alcotest' filter. The build is [passing](https://github.com/MisterDA/mirage-tcpip/runs/4713652258?check_suite_focus=true).

2022-01-05 12:16 UTC, dinosaure approved these changes

2022-01-14 08:25 UTC, MisterDA commented
Could the PR be merged?

2022-01-20 08:30 UTC, merged

2022-01-25 13:00 UTC, dinosaure commented on freestanding/Makefile
> +ifneq (, $(shell command -v opam || which opam))
Yes, on my side I just removed `which`. It seems that such usage does not work for NixOS, do we really need to use it @MisterDA?

2022-01-25 14:58 UTC, MisterDA commented on freestanding/Makefile
> +ifneq (, $(shell command -v opam || which opam))
No it's not needed. i think I copied it from another Makefile.